config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  resources :dishes, except: :destroy do
  	member do
  		put 'like', to: 'dishes#upvote'
  		put 'dislike', to: 'dishes#downvote'
  	end
  end
  post "/dishes/add_new_comment", to: "dishes#add_new_comment", :as => "add_new_comment_to_dishes"
  get 'dishes/:search', to: 'dishes#index'
  get '/user_view_all', to: 'dishes#get_dishes', as: :user_dishes
  put '/user_publish/:id', to: 'dishes#publish', as: :user_publish
  root 'dishes#index'
end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/comment.rb
class Comment < ActiveRecord::Base

  include ActsAsCommentable::Comment

  belongs_to :commentable, :polymorphic => true

  default_scope -> { order('created_at ASC') }

  # NOTE: install the acts_as_votable plugin if you
  # want user to vote on the quality of comments.
  #acts_as_voteable

  # NOTE: Comments belong to a user
  belongs_to :user
end

app/models/dish.rb
class Dish < ActiveRecord::Base
	acts_as_votable
	acts_as_commentable
	belongs_to :user, inverse_of: :dishes

	validates_presence_of :title, :description
	validates_numericality_of :pax, only_integer: true
	validates_numericality_of :cost, greater_than: 0

	scope :approved, -> { where(approved: true) }
	scope :unapproved, -> { where(approved: false) }
	scope :published, -> { where(published: true) }
	scope :search_by_title, -> (keyword) { where("lower(title) LIKE ?", "%#{keyword.downcase}%") }
	scope :search_by_description, -> (keyword) { where("lower(description) LIKE ? ", "%#{keyword.downcase}%") }
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :dishes
  acts_as_voter
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/dishes_controller.rb
class DishesController < ApplicationController	
	before_action :authenticate_user!, except: [:show, :index]

	def index
		@dishes = Dish.published.approved
		@dishes = @dishes.search_by_title(search_params) | @dishes.search_by_description(search_params) if search_params.present?
	end

	def show
		@dish = Dish.find(dish_id)
		@comments = @dish.comments
	end

	def new
		@dish = current_user.dishes.build
	end

	def create
		@dish = current_user.dishes.build(dish_params)
		if @dish.save
			flash[:notice] = "Successful creating"
			redirect_to dish_url(@dish)
		else
			flash[:error] = "There is an error while creating dish"
			render :new
		end
	end

	def update
		@dish = Dish.find(dish_id)
		if @dish.update(dish_params)
			flash[:notice] = "Successful updated"
			redirect_to dish_url(@dish)
		else
			flash[:error] = "Failed to update"
			render :new
		end
	end

	def edit
		@dish = Dish.find(dish_id)
		render :new
	end

	def get_unapproved_dish
		@dish = Dish.unapproved
	end

	def get_dishes
		@dishes = current_user.dishes
	end

	def publish
		@dish = Dish.find(dish_id)
		@dish.published = !@dish.published
		if @dish.save
			flash[:notice] = @dish.published ? "Publish Successfully" : "Unpublish Successfully"
			redirect_to dish_url(@dish)
		else
			flash[:danger] = "Fail to publish the dish"
		end
	end

	def upvote
		@dish = Dish.find(dish_id)
    @dish.upvote_by current_user
   	redirect_to :back
	end

	def downvote
		@dish = Dish.find(dish_id)
    @dish.downvote_by current_user
   	redirect_to :back
	end

	def add_new_comment
		@dish = Dish.find(params[:id])
		comment = @dish.comments.new(params[:comment].permit(:title, :comment, :user_id))
		comment.user_id = current_user.id
    @dish.comments << comment
    redirect_to action: :show, id: @dish

	end

	private
	
	def dish_params
		params.require(:dish).permit(:title, :description, :cost, :pax, :vegetarian, :published, :user_id)
	end

	def comment_params
		params.require(:comment).permit(:title, :comment, :dish_id)
	end

	def dish_id
		params.require(:id)
	end

	def search_params
		params[:search]
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def get_user_email user
		User.find(user).email
	end
end

app/views/dishes/_comment_form.html.slim
.form-group.col-lg-12
  = form_tag add_new_comment_to_dishes_path, method: :post do
    = hidden_field_tag :id, @dish.id
    .form-group
      = label_tag "Title"
      = text_field_tag "comment[title]", nil, class: "form-control"
    .form-group
      = label_tag "Comment"
      = text_area_tag "comment[comment]", nil, class: "form-control"
    = submit_tag "Post Comment"

app/views/dishes/_dish.html.slim
table.table
  tr
    td Dish name:
    td = dish.title
  tr
  	td Description:
    td = dish.description
  tr
    td Cost:
    td = dish.cost
  tr
    td Pax
    td = dish.pax
  tr
    td Vegetarian
    td 
      i.fa class=(dish.vegetarian?  ? "fa-check" : "fa-close")
  tr
    td Created Date
    td = dish.created_at.strftime('%a, %e %b %Y')
  tr
    td Published
    td 
      i.fa.fa-2x class=(dish.published?  ? "fa-check" : "fa-close")
  tr
    td Approved
    td 
      i.fa.fa-2x class=(dish.approved?  ? "fa-check" : "fa-close")
  tr 
    td 
      = link_to like_dish_path(dish), method: :put, class: "btn btn-default btn-sm" do
        span.glyphicon.glyphicon-heart-empty
      = dish.get_upvotes.size
       | - upvotes
    td
      = link_to dislike_dish_path(dish), method: :put , class: "btn btn-default btn-sm" do
        span.glyphicon.glyphicon-thumbs-down
      = dish.get_downvotes.size 
       | - downvotes
- @comments.each do |comment|
  .form-group
    span = comment.title
    - if comment.user_id.present?
      | - 
      span = get_user_email(comment.user_id)
    p = comment.comment
    
= render 'comment_form'
br
.col-lg-12
  - if user_signed_in?
    .btn.btn-default
      = link_to "Edit", edit_dish_path(dish)
    .btn.btn-default
      = link_to (dish.published? ? "Unpublish" : "Publish"), user_publish_path(dish), method: :put
  .btn.btn-default
    = link_to 'Back', :back

app/views/dishes/_form.html.slim
h1  Dish Information
.form-group.col-lg-6
  = form_for(@dish) do |f|
    - if @dish.errors.any?
      .alert.alert-danger
        h2 = pluralize(@dish.errors.count, "error") 
          | prohibited this post from being saved:
        ul
        - @dish.errors.full_messages.each do |msg|
          li
            = msg
    .form-group
      = f.label :title
      = f.text_field :title, class: 'form-control'
    .form-group
      = f.label :description
      = f.text_area :description, class: 'form-control'
    .form-group
      = f.label :vegetarian
      = f.check_box :vegetarian
    .form-group
      = f.label :cost
      = f.number_field :cost, min: 0.5, step: 0.01, class: 'form-control'
    .form-group
      = f.label :pax
      = f.number_field :pax, min: 1, step: 1, class: 'form-control'
    .form-group
      = f.label :published
      = f.check_box :published


    = f.submit "Create", class: 'btn btn-primary'
  = link_to "Back", :back

app/views/dishes/_search.html.slim
= form_tag(dishes_path, method: "get",  class: "navbar-search")
  .input-group.search-dishes-box
  	= text_field_tag :search, nil, placeholder: "Search for...", class: "form-control"
  	span.input-group-btn
  		= submit_tag "Go!", class: "btn btn-primary" 

app/views/dishes/get_dishes.html.slim
- if @dishes.any?
	h1 My Dish
	table.table.table-bordered.dishes#index
		thead
			tr
				th Title
				th.text-center Published
				th Cost
				th Pax
				th.text-center Vegetarian
				th Created Date
				th.text-center Approved
				th.text-center Actions
			tbody
			- @dishes.each do |dish|
				tr 
					td
						= link_to dish.title, dish_path(dish)	
					td.text-center
						i class=(dish.published? ? 'fa fa-2x fa-check' : 'fa fa-2x fa-close') style="color: green;"
					td = number_to_currency dish.cost
					td = dish.pax
					td.text-center
						i class=(dish.vegetarian? ? 'fa fa-check' : 'fa fa-close')
					td = dish.created_at.strftime('%a, %e %b %Y')
					td.text-center
						i class=(dish.approved? ? 'fa fa-2x fa-check' : 'fa fa-2x fa-close') style="color: red;"
					td 
						.btn.btn-link
							= link_to "Details", dish_path(dish)
						.btn.btn-default
							= link_to "Edit", edit_dish_path(dish)
						.btn.btn-default
							= link_to (dish.published? ? "Unpublish" : "Publish"), user_publish_path(dish), method: :put
- else
		.alert.alert-info 
			| No dish found
.btn.btn-default
	= link_to "Back", :back

app/views/dishes/index.html.slim
- if @dishes.any?
	h1 = t('.all_dishes')
	= render partial: 'search'
	#dish-container.transitions-enabled
		- @dishes.each do |dish|
		
			.box.panel.panel-default
				= link_to image_tag('https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQPM5z5ZQhGAqZGxfaYf9eeQ7ncRwyh0jrMPsPnhxqN5sJG3m2wQg'), dish_path(dish)
			.panel-body
				h2 = link_to dish.title, dish_path(dish)
- else
		.alert.alert-info = t('.no_dish')
.btn.btn-default
	= link_to "Back", :back

app/views/dishes/new.html.slim
= render partial: 'form'

app/views/dishes/show.html.slim
h1 Dish Details
= render partial: 'dish', locals: { dish: @dish }

app/views/layouts/application.html.slim
doctype html
html
  head
    title Ramsayfantitle
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags 
  head
  body
    nav.navbar.navbar-default.navbar-static-top
      .container
        .navbar-header
          = link_to "RamsayFan", root_path, class:"navbar-brand" 
        div
          ul class="nav navbar-nav navbar-right"
            = render "devise/menu/dishes"
            = render "devise/menu/registration_items"
            = render "devise/menu/log_in_items"
    .container
      - flash.each do |key, value| 
        -if flash[:notice] or flash[:success]
          .alert.alert-success
            = flash[:notice]
        - else
          .alert.alert-danger
            = value
      = yield